<#
.SYNOPSIS
    Installs this vault's user-level memory file to ~/.claude/CLAUDE.md.

.DESCRIPTION
    Renders user-memory/CLAUDE.md.template into ~/.claude/CLAUDE.md, resolving
    the vault's absolute path on THIS machine so the @imports work wherever the
    vault is checked out. The work laptop and the home machine keep the vault in
    different folders, so the path cannot be hard-coded.

    The vault is the source of truth. Edit the template, never ~/.claude/CLAUDE.md —
    this script overwrites it.

    Any existing ~/.claude/CLAUDE.md that was NOT generated by this script is
    backed up before being replaced.

.PARAMETER Check
    Report what would change without writing anything.

.EXAMPLE
    .\install.ps1
    .\install.ps1 -Check
#>
#Requires -Version 5.1
[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$TemplatePath = Join-Path $PSScriptRoot 'CLAUDE.md.template'
# The vault root is the parent of this script's folder.
$VaultRoot  = Split-Path -Parent $PSScriptRoot
$ClaudeHome = Join-Path $env:USERPROFILE '.claude'
$Target     = Join-Path $ClaudeHome 'CLAUDE.md'

$MarkerText = 'Generated from user-memory/CLAUDE.md.template'

Write-Host "user-memory installer" -ForegroundColor Cyan
Write-Host "  template: $TemplatePath"
Write-Host "  vault:    $VaultRoot"
Write-Host "  target:   $Target"
Write-Host ""

if (-not (Test-Path -LiteralPath $TemplatePath)) {
    Write-Host "template not found: $TemplatePath" -ForegroundColor Red
    exit 1
}

# Sanity-check that the resolved vault root really is the vault, so a misplaced
# copy of this script cannot point the imports at the wrong folder.
foreach ($required in @('CLAUDE.md', 'README.md')) {
    if (-not (Test-Path -LiteralPath (Join-Path $VaultRoot $required))) {
        Write-Host "$required not found in $VaultRoot — is this the vault root?" -ForegroundColor Red
        exit 1
    }
}

# @import paths use forward slashes; the prose shows the native Windows path.
$vaultPosix = $VaultRoot -replace '\\', '/'
$rendered = (Get-Content -LiteralPath $TemplatePath -Raw).
    Replace('{{VAULT_POSIX}}', $vaultPosix).
    Replace('{{VAULT_WIN}}', $VaultRoot)

# Fail loudly rather than install a file with unresolved placeholders.
if ($rendered -match '\{\{[A-Z_]+\}\}') {
    Write-Host "unresolved placeholder left in rendered output:" -ForegroundColor Red
    [regex]::Matches($rendered, '\{\{[A-Z_]+\}\}') |
        Select-Object -ExpandProperty Value -Unique |
        ForEach-Object { Write-Host "  $_" -ForegroundColor Red }
    exit 1
}

$existing = if (Test-Path -LiteralPath $Target) { Get-Content -LiteralPath $Target -Raw } else { $null }

if ($null -ne $existing -and $existing -eq $rendered) {
    Write-Host "  unchanged  CLAUDE.md is already current" -ForegroundColor DarkGray
    Write-Host ""
    Write-Host "done: 0 written, 1 unchanged" -ForegroundColor Cyan
    exit 0
}

# Preserve anything hand-written that this script did not generate.
if ($null -ne $existing -and $existing -notmatch [regex]::Escape($MarkerText)) {
    $backup = "$Target.bak.$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Write-Host "  backup     existing hand-written CLAUDE.md -> $(Split-Path -Leaf $backup)" -ForegroundColor Yellow
    if (-not $Check) { Copy-Item -LiteralPath $Target -Destination $backup }
}

$verb = if ($null -eq $existing) { 'add    ' } else { 'update ' }
Write-Host "  $verb   CLAUDE.md$(if ($Check) { '  (dry run)' })" -ForegroundColor Green
Write-Host "             imports -> $vaultPosix/CLAUDE.md, $vaultPosix/README.md"

if ($Check) {
    Write-Host ""
    Write-Host "dry run: 1 to write. Re-run without -Check to apply."
    exit 0
}

New-Item -ItemType Directory -Force -Path $ClaudeHome | Out-Null
Set-Content -LiteralPath $Target -Value $rendered -NoNewline -Encoding UTF8

Write-Host ""
Write-Host "done: 1 written" -ForegroundColor Cyan
Write-Host ""
Write-Host "Restart Claude Code (or start a new session) to load it."
